apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ template "k8s-crdguard.fullname" $ }}
  labels:
{{- include "k8s-crdguard.labels" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "k8s-crdguard.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ template "k8s-crdguard.fullname" $ }}
    namespace: {{ .Release.Namespace }}