apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "k8s-crdguard.fullname" $ }}
  labels:
{{- include "k8s-crdguard.labels" $ | indent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - list
