apiVersion: v1
kind: Service
metadata:
  name:  {{ template "k8s-crdguard.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{- include "k8s-crdguard.labels" $ | indent 4 }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: web
  selector:
{{- include "k8s-crdguard.selectorlabels" $ | indent 4 }}