patchCertificates:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
  image:
    repository: jettech/kube-webhook-certgen
    tag: v1.2.0
    pullPolicy: IfNotPresent

image:
  repository: vsliouniaev/k8s-crdguard
  tag: v0.0.1
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 110Mi

## Explicit list of CRDs to prevent deletion of default is to block everything.
## Name must be the full name like 'prometheuses.monitoring.coreos.com'
crds: []
